Introduce `groupinds!` function to group parallel inds
bsc-quantic/Tenet.jl pull request #199
Opened 2024-09-07 18:52 UTC by mofeing

CC @starsfordummies

2024-09-07 20:05 UTC, starsfordummies approved these changes
\o/

2024-09-09 10:11 UTC, jofrevalles requested changes

2024-09-09 10:11 UTC, jofrevalles commented on src/TensorNetwork.jl
> +Group indices parallel to `i` and reshape the tensors to reflect it.
```suggestion
Group indices parallel to `i` and reshape the tensors accordingly.
```

2024-09-09 10:12 UTC, jofrevalles commented
Shouldn't we indicate which indices should the function group? Like `:i` and `:j`, and not only those who are "parallel to" `:i`?

2024-09-09 14:10 UTC, mofeing commented
I see your point, but we are only going to "group" indices that are parallel; grouping indices that are not parallel involves performing contractions of the involved tensors, which we don't want to force.

2024-09-10 13:05 UTC, merged