Fix plots for `TensorNetworks` with hyperedges
bsc-quantic/Tenet.jl pull request #31
Opened 2023-02-23 15:52 UTC by jofrevalles

From issue #21 

### Summary
In this PR we fix the `plot` functions: now these can plot `TensorNetworks` with hyperedges. The hyperedges are visualized with a grey diamond-shaped COPY tensor, with grey indices coming from it.

### Example
```julia
julia> using Tenet
julia> using GLMakie
julia> using Makie
julia> tn = TensorNetwork([Tensor(rand([2, 2, 2]...), tuple([:i, :c, :k]...)), Tensor(rand([2, 2, 2, 2]...), tuple([:i, :k, :s, :p]...)), Tensor(rand([2, 2, 2]...), tuple([:i, :s, :c]...)), Tensor(rand([2, 2]...), tuple([:p, :t]...))])
TensorNetwork{Arbitrary}(#tensors=4, #inds=6)
julia> plot(tn; labels=true)
(Scene (800px, 600px):
  0 Plots
  1 Child Scene:
    └ Scene (800px, 600px), Axis (1 plots), Combined{GraphMakie.graphplot, Tuple{Graphs.SimpleGraphs.SimpleGraph{Int64}}})
julia> [tensor.labels for tensor in tn.tensors]
4-element Vector{Tuple{Symbol, Symbol, Vararg{Symbol}}}:
 (:i, :c, :k)
 (:i, :k, :s, :p)
 (:i, :s, :c)
 (:p, :t)
```
![Screenshot from 2023-02-23 16-51-13](https://user-images.githubusercontent.com/61060572/220959517-ef1c48d1-320b-4fd4-95df-321910d6b2a3.png)

2023-02-23 15:54 UTC, jofrevalles commented
PD: Still working in 3D.

![image](https://user-images.githubusercontent.com/61060572/220960176-90a1e11c-8dcb-4080-af25-5c6f55eb38c8.png)

2023-02-23 15:59 UTC, mofeing requested changes
Nice! Just requested some changes. Also, the grey color doesn't convince me. What about leaving them black but regular tensors are drawn as "white circles with black circumference" and lil bit bigger?

2023-02-23 15:59 UTC, mofeing commented on src/Visualization.jl
> +    transform!(tn, HyperindConverter)
If you use `transform!`, you're modifying the `TensorNetwork` of the user. Just do a shallow copy of it (tensors are copied but their arrays not).
```suggestion
    # NOTE hyper edges cannot be easily drawn. transform them into COPY-tensors instead.
    tn = transform(tn, HyperindConverter)
```

2023-02-24 10:06 UTC, jofrevalles commented
Okey, now it looks something like this:
![image](https://user-images.githubusercontent.com/61060572/221151232-37d420eb-76ea-476d-9739-07b3f6bc1d21.png)

2023-02-24 10:29 UTC, mofeing approved these changes

2023-02-24 10:29 UTC, merged